[package]
name = "smartbeans-backend"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
lazy_static = "1.4.0"
config = "0.11.0"