[package]
name = "smartbeans-backend"
version = "0.1.0"
authors = ["Niklas Birth <birth@posteo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.6"
serde_json = "1.0.59"
dotenv = "0.15.0"
rand = "0.7.3"
diesel = { version = "1.4.5", features = ["sqlite"] }
diesel_migrations = "1.4.0"
rocket_cors = "0.5.2"
colored = "2.0.0"
serde_urlencoded = "0.7.0"
hmac = "0.10.1"
base64 = "0.13.0"
crypto-hashes = { version = "0.9.0", features = ["include_weak"] }
percent-encoding = "2.1.0"
reqwest = { version = "0.10.9", features = ["blocking", "json"] }

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json", "diesel_sqlite_pool"]