[rocket]
# If provided, this settings will override settings provided in Rocket.toml or environment variables.
# address = "127.0.0.1"
# port = "8000"
# log_level = "normal"

[database]
host = "localhost"
port = 3306 # not sure if changing this actually has any effect
user = "smartbeans"
password = "smartbeans"
database = "smartbeans"

[sandbox]
urls = [
    "https://someurl:1234"
]

[auth]
# Seconds until a session expires, if not refreshed by a route call
session_duration = 3600
# Currently used for adding tasks and accessing debug auth route.
# Comment out to disable the it (and let routes that require it return a 403).
# admin_key = "change me"

[auth.lti]
# LTI consumer secret
secret = "secret"
# In general, this should be http(s)://<backend-URL>/auth/login/lti
url = "https://smartbeans.example.com/api/auth/login/lti"
# URL for redirect after LTI validation
redirect = "https://smartbeans.example.com/lti"

[auth.password]
registration_keys = ["some_key", "another_one"]
key_required = true